### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.gson.JsonObject.size()I

### ISSUE THREAD

**Issue by andrewlu1** [bmob/bmob-java-sdk#2]
Exception in thread "main" java.lang.NoSuchMethodError: com.google.gson.JsonObject.size()I
	at cn.bmob.data.utils.Utils.getDataObject(Utils.java:344)
	at cn.bmob.data.utils.Utils.getJsonObjectRequest(Utils.java:417)
	at cn.bmob.data.bean.table.BmobObject.save(BmobObject.java:326)
	at cn.andrewlu.net_test.MainAppKt.main(MainApp.kt:30)

**Comment by andrewlu1** [comment]
找到原因了,是我自己lib里 添加了一个低版本的gson依赖.

**Comment by jskrnbindra** [comment]
Facing the same, what was the issue?
